<?xml version="1.0" standalone="yes"?>
<!DOCTYPE powerforms [
<!ELEMENT powerforms (version,date,count,form)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT count (#PCDATA)>
<!ELEMENT form (properties,attributes,fields,fieldopts)>
<!ELEMENT properties (form_id,name,alias)>
<!ELEMENT form_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT attributes (attribute)>
<!ELEMENT attribute (form_attr_id,name,value)>
<!ELEMENT form_attr_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT fields (field)>
<!ELEMENT field (field_id,name,type,validation_type,required,hide_label,order_by,option)>
<!ELEMENT field_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT validation_type (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT hide_label (#PCDATA)>
<!ELEMENT order_by (#PCDATA)>
<!ELEMENT option (option_id,name,value)>
<!ELEMENT option_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
]>
<powerforms>
	<version>0.7</version>
	<date></date>
	<count>1</count>
	<form>
		<properties>
			<form_id>2</form_id>
			<name>Advanced Contact Form</name>
			<alias>advanced_contact</alias>
		</properties>
		<attributes>
			<attribute>
				<form_attr_id>24</form_attr_id>
				<name>list_delimiter</name>
				<value>,</value>
			</attribute>
			<attribute>
				<form_attr_id>25</form_attr_id>
				<name>css_class</name>
				<value>advancedcontactform</value>
			</attribute>
			<attribute>
				<form_attr_id>26</form_attr_id>
				<name>submit_action</name>
				<value>text</value>
			</attribute>
			<attribute>
				<form_attr_id>27</form_attr_id>
				<name>validate_udt</name>
				<value>-1</value>
			</attribute>
			<attribute>
				<form_attr_id>28</form_attr_id>
				<name>submission_template</name>
				<value><p>Thank you, <strong>{$your_name}</strong>.</p>
<p>Your submission has been successful. You may wish to print this page as a reference.</p>
<h3>Contact Details</h3>
<p>
<strong>Name</strong>: {$your_name}<br />
<strong>Email</strong>: <a href="mailto:{$your_email_address}">{$your_email_address}</a><br />
</p>
<h3>Feedback Details</h3>
<p>
<strong>Subject</strong>: {$subject}<br />
<strong>Comments</strong>:<br />
{$message}
</p> 
<h4>Other information</h4>
<p>
<strong>Date of submission</strong>: {$sub_date}<br />
<strong>IP address from which form was submitted</strong>: {$sub_source}<br />
<strong>Form host</strong>: {$form_host}<br />
<strong>URL of page containing form</strong>: {$form_url}<br />
<strong>Form name</strong>: {$form_name}
</p></value>
			</attribute>
			<attribute>
				<form_attr_id>29</form_attr_id>
				<name>predisplay_udt</name>
				<value>-1</value>
			</attribute>
			<attribute>
				<form_attr_id>30</form_attr_id>
				<name>form_template</name>
				<value>{* DEFAULT FORM LAYOUT / pure CSS *}
{if $form_done}
	{* This section is for displaying submission errors *}
	{if !empty($submission_error)}
		<div class="error_message">{$submission_error}</div>
		{if !empty($show_submission_errors)}
			<div class="error">
			<ul>
			{foreach from=$submission_error_list item=one}
				<li>{$one}</li>
			{/foreach}
			</ul>
		</div>
		{/if}
	{/if}
{else}
	{* This section is for displaying the form *}
	{* we start with validation errors *}
	{if !empty($form_has_validation_errors)}
		<div class="error_message">
		<ul>
		{foreach from=$form_validation_errors item=one}
			<li>{$one}</li>
		{/foreach}
		</ul>
		</div>
	{/if}
	{if !empty($captcha_error)}
		<div class="error_message">{$captcha_error}</div>
	{/if}
	{* and now the form itself *}
	{$form_start}
	<h4 style="text-align:center;">Order</h4>
	<div>{$hidden}</div>
	<div{if $css_class != ''} class="{$css_class}"{/if}>
	{if $total_pages gt 1}<span>{$title_page_x_of_y}</span>{/if}
	{foreach from=$fields item=one}
		{strip}
		{if $one->display}
		 	{if $one->needs_div}
				<div
				{if $one->required || $one->css_class != '' || !$one->valid} class="
{if $one->required}required{/if}{if $one->css_class} {$one->css_class}{/if}{if !$one->valid} pwf_invalid{/if}
"
				{/if}
				>
		 	{/if}
		 	{if !$one->hide_name}
				<label{if $one->multiple_parts != 1} for="{$one->input_id}"{/if}>{$one->name}
				{if $one->required_symbol != ''}
			   		{$one->required_symbol}
				{/if}
				</label>
		 	{/if}
		 	{if $one->multiple_parts}
				{section name=numloop loop=$one->input}
			   		{if $one->label_parts}
			   			<div>{$one->input[numloop]->input}&nbsp;{$one->input[numloop]->name}</div>
			   		{else}
			   			{$one->input[numloop]->input}
			   		{/if}
			   		{if !empty($one->input[numloop]->op)}{$one->input[numloop]->op}{/if}
				{/section}
		 	{else}
				{if $one->smarty_eval}{eval var=$one->input}{else}{$one->input}{/if}
		 	{/if}
		 	{if !$one->valid} &lt;--- {$one->error}{/if}
		 	{if $one->needs_div}
				</div>
		 	{/if}
	 	{/if}
	 	{/strip}
	{/foreach}
	{if !empty($has_captcha)}
		<div class="captcha">{$graphic_captcha}<br />{$title_captcha}<br />{$input_captcha}<br /></div>
	{/if}
	<div class="submit">{$prev}{$submit}</div>
	</div>
	{$form_end}
{/if}</value>
			</attribute>
			<attribute>
				<form_attr_id>31</form_attr_id>
				<name>redirect_page</name>
				<value>-1</value>
			</attribute>
			<attribute>
				<form_attr_id>32</form_attr_id>
				<name>input_button_safety</name>
				<value>0</value>
			</attribute>
			<attribute>
				<form_attr_id>33</form_attr_id>
				<name>submit_button_text</name>
				<value>Submit Form</value>
			</attribute>
			<attribute>
				<form_attr_id>34</form_attr_id>
				<name>unspecified</name>
				<value>[unspecified]</value>
			</attribute>
			<attribute>
				<form_attr_id>35</form_attr_id>
				<name>required_field_symbol</name>
				<value>*</value>
			</attribute>
			<attribute>
				<form_attr_id>36</form_attr_id>
				<name>captcha_wrong</name>
				<value>The entered text was not correct.</value>
			</attribute>
			<attribute>
				<form_attr_id>37</form_attr_id>
				<name>prev_button_text</name>
				<value>Back...</value>
			</attribute>
			<attribute>
				<form_attr_id>38</form_attr_id>
				<name>use_captcha</name>
				<value>0</value>
			</attribute>
			<attribute>
				<form_attr_id>39</form_attr_id>
				<name>inline</name>
				<value>0</value>
			</attribute>
			<attribute>
				<form_attr_id>40</form_attr_id>
				<name>submit_javascript</name>
				<value></value>
			</attribute>
			<attribute>
				<form_attr_id>41</form_attr_id>
				<name>next_button_text</name>
				<value>Continue...</value>
			</attribute>
			<attribute>
				<form_attr_id>42</form_attr_id>
				<name>title_user_captcha</name>
				<value>Help prevent abuse by spammers, enter the text from the image.</value>
			</attribute>
			<attribute>
				<form_attr_id>43</form_attr_id>
				<name>predisplay_each_udt</name>
				<value>-1</value>
			</attribute>
		</attributes>
		<fields>
			<field>
				<field_id>9</field_id>
				<name>About You Fieldset</name>
				<type>FieldsetStart</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>1</order_by>
				<option>
					<option_id>76</option_id>
					<name>legend</name>
					<value>About You</value>
				</option>
				<option>
					<option_id>77</option_id>
					<name>css_class</name>
					<value></value>
				</option>
				<option>
					<option_id>78</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
				<option>
					<option_id>79</option_id>
					<name>helptext</name>
					<value></value>
				</option>
				<option>
					<option_id>80</option_id>
					<name>javascript</name>
					<value></value>
				</option>
			</field>
			<field>
				<field_id>10</field_id>
				<name>Your Name</name>
				<type>FromEmailNameField</type>
				<validation_type></validation_type>
				<required>1</required>
				<hide_label>0</hide_label>
				<order_by>2</order_by>
				<option>
					<option_id>81</option_id>
					<name>css_class</name>
					<value></value>
				</option>
				<option>
					<option_id>82</option_id>
					<name>field_alias</name>
					<value>users_name</value>
				</option>
				<option>
					<option_id>83</option_id>
					<name>helptext</name>
					<value></value>
				</option>
				<option>
					<option_id>84</option_id>
					<name>javascript</name>
					<value></value>
				</option>
			</field>
			<field>
				<field_id>11</field_id>
				<name>Your Email Address</name>
				<type>DispositionFromEmailAddressField</type>
				<validation_type>none</validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>3</order_by>
				<option>
					<option_id>85</option_id>
					<name>email_subject</name>
					<value>Email from Site</value>
				</option>
				<option>
					<option_id>86</option_id>
					<name>email_from_name</name>
					<value>Power Forms</value>
				</option>
				<option>
					<option_id>87</option_id>
					<name>send_user_copy</name>
					<value>c</value>
				</option>
				<option>
					<option_id>88</option_id>
					<name>send_user_label</name>
					<value>Send me a copy of form</value>
				</option>
				<option>
					<option_id>89</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
				<option>
					<option_id>90</option_id>
					<name>javascript</name>
					<value></value>
				</option>
				<option>
					<option_id>91</option_id>
					<name>html_email</name>
					<value></value>
				</option>
				<option>
					<option_id>92</option_id>
					<name>email_template</name>
					<value>PowerForms Submission
Date of submission: {$sub_date}
IP address of from which form was submitted: {$sub_source}
Form name: {$form_name}
Form host: {$form_host}
URL of page containing form: {$form_url}
PowerForms version: {$version}
->
----------------------------------------------
Your Name: {$fld_12}
Your Email Address: {$fld_43}
Email Again: {$fld_42}
Subject: {$fld_17}
Message: {$fld_18}</value>
				</option>
				<option>
					<option_id>93</option_id>
					<name>email_encoding</name>
					<value>utf-8</value>
				</option>
			</field>
			<field>
				<field_id>12</field_id>
				<name>Email Again</name>
				<type>FromEmailAddressAgainField</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>4</order_by>
				<option>
					<option_id>94</option_id>
					<name>field_to_validate</name>
					<value>Your Email Address</value>
				</option>
				<option>
					<option_id>95</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
				<option>
					<option_id>96</option_id>
					<name>css_class</name>
					<value></value>
				</option>
			</field>
			<field>
				<field_id>13</field_id>
				<name>About You Fieldset End</name>
				<type>FieldsetEnd</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>5</order_by>
				<option>
					<option_id>97</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
				<option>
					<option_id>98</option_id>
					<name>css_class</name>
					<value></value>
				</option>
				<option>
					<option_id>99</option_id>
					<name>helptext</name>
					<value></value>
				</option>
			</field>
			<field>
				<field_id>14</field_id>
				<name>breaker</name>
				<type>PageBreakField</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>6</order_by>
				<option>
					<option_id>100</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
			</field>
			<field>
				<field_id>15</field_id>
				<name>Contact Fieldset</name>
				<type>FieldsetStart</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>7</order_by>
				<option>
					<option_id>101</option_id>
					<name>legend</name>
					<value>Contact</value>
				</option>
				<option>
					<option_id>102</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
				<option>
					<option_id>103</option_id>
					<name>css_class</name>
					<value></value>
				</option>
				<option>
					<option_id>104</option_id>
					<name>helptext</name>
					<value></value>
				</option>
				<option>
					<option_id>105</option_id>
					<name>javascript</name>
					<value></value>
				</option>
			</field>
			<field>
				<field_id>16</field_id>
				<name>Greeting</name>
				<type>StaticTextField</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>8</order_by>
				<option>
					<option_id>106</option_id>
					<name>text</name>
					<value>Hello, {$users_name->value}!<br /> What is it you'd like to talk to us about?</value>
				</option>
				<option>
					<option_id>107</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
				<option>
					<option_id>108</option_id>
					<name>css_class</name>
					<value></value>
				</option>
				<option>
					<option_id>109</option_id>
					<name>helptext</name>
					<value></value>
				</option>
				<option>
					<option_id>110</option_id>
					<name>javascript</name>
					<value></value>
				</option>
				<option>
					<option_id>111</option_id>
					<name>smarty_eval</name>
					<value>1</value>
				</option>
			</field>
			<field>
				<field_id>17</field_id>
				<name>Subject</name>
				<type>FromEmailSubjectField</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>9</order_by>
				<option>
					<option_id>112</option_id>
					<name>css_class</name>
					<value></value>
				</option>
			</field>
			<field>
				<field_id>18</field_id>
				<name>Message</name>
				<type>TextAreaField</type>
				<validation_type></validation_type>
				<required>1</required>
				<hide_label>0</hide_label>
				<order_by>10</order_by>
				<option>
					<option_id>113</option_id>
					<name>rows</name>
					<value>5</value>
				</option>
				<option>
					<option_id>114</option_id>
					<name>cols</name>
					<value>60</value>
				</option>
				<option>
					<option_id>115</option_id>
					<name>css_class</name>
					<value></value>
				</option>
				<option>
					<option_id>116</option_id>
					<name>field_alias</name>
					<value>message</value>
				</option>
				<option>
					<option_id>117</option_id>
					<name>default</name>
					<value>Enter Your Message Here</value>
				</option>
				<option>
					<option_id>118</option_id>
					<name>clear_default</name>
					<value>1</value>
				</option>
			</field>
			<field>
				<field_id>19</field_id>
				<name>Send To</name>
				<type>DispositionEmail</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>11</order_by>
				<option>
					<option_id>119</option_id>
					<name>email_subject</name>
					<value>Contact Form Submission</value>
				</option>
				<option>
					<option_id>120</option_id>
					<name>email_from_name</name>
					<value>Power Forms</value>
				</option>
				<option>
					<option_id>121</option_id>
					<name>email_from_address</name>
					<value>me@overhere.com</value>
				</option>
				<option>
					<option_id>122</option_id>
					<name>destination_address</name>
					<value>you@overthere.net</value>
				</option>
				<option>
					<option_id>123</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
				<option>
					<option_id>124</option_id>
					<name>html_email</name>
					<value>1</value>
				</option>
				<option>
					<option_id>125</option_id>
					<name>email_template</name>
					<value><h1>PowerForms Submission</h1>
<strong>Date of submission</strong>: {$sub_date}<br />
<strong>IP address from which form was submitted</strong>: {$sub_source}<br />
<strong>Form host</strong>: {$form_host}<br />
<strong>URL of page containing form</strong>: {$form_url}<br />
<strong>Form name</strong>: {$form_name}<br />
<strong>PowerForms version</strong>: {$version}<br />
<hr />
{if $fld_10 != "" && $fld_10 != "[unspecified]"}<strong>Your Name</strong>: {$fld_10}<br />{/if}
{if $fld_11 != "" && $fld_11 != "[unspecified]"}<strong>Your Email Address</strong>: {$fld_11}<br />{/if}
{if $fld_12 != "" && $fld_12 != "[unspecified]"}<strong>Email Again</strong>: {$fld_12}<br />{/if}
{if $fld_17 != "" && $fld_17 != "[unspecified]"}<strong>Subject</strong>: {$fld_17}<br />{/if}
{if $fld_18 != "" && $fld_18 != "[unspecified]"}<strong>Message</strong>: {$fld_18}<br />{/if}
{if $fld_19 != "" && $fld_19 != "[unspecified]"}<strong>Send To</strong>: {$fld_19}<br />{/if}</value>
				</option>
				<option>
					<option_id>126</option_id>
					<name>email_encoding</name>
					<value>utf-8</value>
				</option>
			</field>
			<field>
				<field_id>20</field_id>
				<name>Contact Fieldset End</name>
				<type>FieldsetEnd</type>
				<validation_type></validation_type>
				<required>0</required>
				<hide_label>0</hide_label>
				<order_by>12</order_by>
				<option>
					<option_id>127</option_id>
					<name>field_alias</name>
					<value></value>
				</option>
				<option>
					<option_id>128</option_id>
					<name>css_class</name>
					<value></value>
				</option>
				<option>
					<option_id>129</option_id>
					<name>helptext</name>
					<value></value>
				</option>
			</field>
		</fields>
	</form>
</powerforms>
